name: thrive
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:                                          # State management
  isar:                                                 # Database
  isar_flutter_libs:                            # Flutter support for Isar
  path_provider:                                # Access to the filesystem
  intl:                                                 # Internationalization and localization
  flutter_slidable:                             # Slidable list items

dev_dependencies:
  flutter_test:                                  # Flutter testing framework
    sdk: flutter                                  
  flutter_lints: ^3.0.0                       # Linting rules for Flutter projects
  isar_generator:                              # Code generation for Isar
  build_runner:                                 # Build system for code generation

flutter:
  uses-material-design: true             # Enables material design
